# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish images

permissions: {}

on:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    outputs:
      image-digest: ${{ steps.publish-kyverno-notation-venafi.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
        with:
          build-cache-key: publish-images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca # v0.16.1
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
      - name: Install Cosign
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 # v3.3.0
      - name: Publish image
        id: publish-kyverno-notation-venafi
        uses: ./.github/actions/publish-image
        with:
          makefile-target: docker-publish
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository_owner }}
          version: ${{ github.ref_name }}
          sign-image: true
          sbom-name: kyverno-notation-venafi
          sbom-repository: ghcr.io/${{ github.repository }}/sbom
          signature-repository: ghcr.io/${{ github.repository }}/signatures
          main-path: ./
          image-tag: ${{ github.sha }}

  generate-kyverno-notation-venafi-provenance:
    needs: publish-images
    permissions:
      id-token: write # To sign the provenance.
      packages: write # To upload assets to release.
      actions: read # To read the workflow path.
    # NOTE: The container generator workflow is not officially released as GA.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.9.0
    with:
      image: ghcr.io/${{ github.repository_owner }}/kyverno-notation-venafi
      digest: "${{ needs.publish-images.outputs.image-digest }}"
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

